### ISSUE TITLE
Allow scrollable element to be configured.

### ISSUE THREAD

**Issue by terryroe** [jasonkriss/ember-infinite-scroll#7]
Jason,

Do you have any plans, or can you suggest a way, to configured the scrollable element?  It's currently set to the window.  However, I need to have a scrollable element that is a div within the page.  It's actually quite close to working as is, but it does not work in IE 11.  When I scroll my scrollable element in Chrome, the whole page "attempts" to scroll slightly, and I think that's why it is working in Chrome.  However, IE 11 doesn't have that same behavior; the window/page doesn't move at all.  I think being able to specify the scrollable element would be a nice addition, and would probably solve this problem.

Thanks,

TR

**Comment by terryroe** [comment]
It looks like Firefox has the same behavior as IE.  Just FYI.

**Comment by SirZach** [comment]
you should be able to do {{#infinite-scroll tagName="<desired_element>"}} and specify the element it renders. Also, it's not set to the window, it's rendered like any other ember component.

**Comment by jasonkriss** [comment]
@SirZach I think @terryroe means that he wants to have just a part of the page be infinitely scrollable. This seems like a fairly common use case to me, so I just added it [here](https://github.com/jasonkriss/ember-infinite-scroll/commit/ba74bb25ac80ab7cffa4dc1934a006d483f2eae7). @terryroe Sorry for the super slow response!
